
const HeroesSkillsAndTalents = [
    {
        name: "Gregory",
        skillonename: "Agitation",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Increases Basic Attack Damage of up to 4 ally troops in a circular range by 45% for 5 seconds. Also has a 100% chance to inflict Bleed on the target, dealing continuous damage every second (Damage Facor 300) for 2 seconds.",
        skilltwoname: "Drumming Disturbance",
        skilltwotype: "Passive",
        skilltwoprob: 20,
        skilltwodescr: "When the deployed Troop does a Basic Attack, there is a 20% chance of Healing Lightly Wounded units (Heal Factor 250) every second for 2s, durng which the targets Active Skill Damage is reduced by 10%.",
        skillawakename: "Inspiring Dance",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Increases Basic Attack Damage of up to 5 ally troops in a circular range by 50% for 5 seconds. Also has a 100% chance to inflict Bleed on the target, dealing continuous damage every second (Damage Facor 400) for 2 seconds.",
        talentonename: "Great Morale",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Basic Attack Damage by 30%",
        talenttwoname: "Missing Beat",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troop performs a basic attack, there is a 20% chance to deal direct damage 1 time (Damage Factor 400) to the target. Damage has a 25% chance to cause target to be Slowed, reducing March Speed by 10% for 2s.",
        talentthreename: "Excite",
        talentthreetype: "Cooperation",
        talentthreedescr: "When deployed Troops use an Active Skill, there is a 40% chance to deal direct damage 1 time (Damage Factor 1800) to the target.",
        id: 1
    },
    {
        name: "Harald",
        skillonename: "Slicing Crush",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 1500) to the target and inflicts them with Slow, reducing their March Speed by 20% for 3s.",
        skilltwoname: "Fleet raider",
        skilltwotype: "Cooperation",
        skilltwoprob: 20,
        skilltwodescr: "When the deployed Troop does a Basic Attack, there is a 20% chance of dealing direct damage 1 time (Damage Factor 300) to the target. When deployed Troops deal damage, increases their Basic Attack Damage by 25% for 5s.",
        skillawakename: "Raging Smash",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 2000) to the target and inflicts them with Slow, reducing their March Speed by 25% for 4s.",
        talentonename: "Battle Preparation",
        talentonetype: "Passive",
        talentonedescr: "Trigger when entering battle, increases deployed Troops Basic Attack Damage by 45% for 30s. Also grants them immunity to Disarm for 30s",
        talenttwoname: "Coordinated Strike",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troops does a basic attack, there is  20% chance of dealing direct damage 1 time (Damage Factor 300) to the target. When deployed Troops deal damage, increases their Cooperation skill Damage by 12% for 3s.",
        talentthreename: "Slow Strike",
        talentthreetype: "Cooperation",
        talentthreedescr: "Increases deployed Troops Basic Attack Damage by 50%. If the Troops are Slowed there is a 30% chance to deal direct damage to the target during a basic attack (Damage Factor 600).",
        id: 2
    },
    {
        name: "Lagertha",
        skillonename: "Parry",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals direct damage 1 time (Damage Factor 1000) to the target, inflicting Bleed, which deals continuous damage every second (Damage Factor 145) for 3s. Also has a 100% chance to grant deployed Troops a shield (Shield Factor 425) for 3s.",
        skilltwoname: "Shield Breaker",
        skilltwotype: "Cooperation",
        skilltwoprob: 20,
        skilltwodescr: "When the deployed Troop does a basic attack, there is a 20% chance of dealing 1 instance of direct damage to the target (Damage Factor 550). If the target is Bleeding, the Troops Basic Attack Damage is further increased by 50% for 2s",
        skillawakename: "Showdown",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals direct damage 1 time (Damage Factor 1500) to the target, inflicting Bleed, which deals continuous damage every second (Damage Factor 150) for 3s. Also has a 100% chance to grant deployed Troops a shield (Shield Factor 800) for 3s.",
        talentonename: "Shieldaxe Attack",
        talentonetype: "Passive",
        talentonedescr: "Increases Bleed Damage by 25%",
        talenttwoname: "Chiefs Might",
        talentwotype: "Cooperation",
        talenttwodescr: "When your deployed Troops deal basic attacks, there is a 20% chance to inflict Bleed on the target, dealing continuous damage every second (Damage Factor 400) for 2s.",
        talentthreename: "Fatal Strike",
        talentthreetype: "Cooperation",
        talentthreedescr: "If the target is Slowed, there is a 50% chance for the deployed Troops to deal direct damage 1 time (Damage Factor 1000) to the target when using a basic attack.",
        id: 3
    },
    {
        name: "Rollo",
        skillonename: "Full Plunder",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 975) to the target and inflicts them with Bleed. Bleeding enemies will take continuous damage every second (Damage Factor 230) for 2s.",
        skilltwoname: "Tough Choice",
        skilltwotype: "Cooperation",
        skilltwoprob: 100,
        skilltwodescr: "Increases deployed Troops Basic Attack Damage by 30%, but decreases Counterattack Damage by 30%. When performing a basic attack, if the target is Slowed, there is a 20% chance for your own Troop to receive healing 1 time (Heal Factor 900).",
        skillawakename: "Bloody Pillage",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1500) to the target and inflicts them with Bleed. Bleeding enemies will take continuous damage every second (Damage Factor 350) for 2s.",
        talentonename: "Patient and Waiting",
        talentonetype: "Passive",
        talentonedescr: "Triggers when entering battle, increases deployed Troops Basic Attack Damage by 20% and there is a 50% chance of dealing direct damage 1 time (Damage Factor 500) to the target for 30s",
        talenttwoname: "Revolutionary Resolve",
        talentwotype: "Cooperation",
        talenttwodescr: "When your deployed Troops use an Active Skill there is a 40% chance to deal 1 instance of direct damage (Damage Factor 1500) to the target and inflicts them with slow, reducing their March Speed by 20% for 2s",
        talentthreename: "Adaptable Agility",
        talentthreetype: "Cooperation",
        talentthreedescr: "If deployed Troops are greater than target Troops, basic attacks have a 25% chance to inflict direct damage to target once (Damage Factor 900). If deployed Troops are less than target Troops, basic attacks have a 20% chance of healing your own Troop 1 time (Heal Factor 500)",
        id: 4
    },
    {
        name: "Jens",
        skillonename: "Sacred Strike",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Inflicts drect damage in a fan shape to up to 5 target Troops once (Damage Factor 600), and increases targets damage received from basic attacks by 7,5% for 4s.",
        skilltwoname: "Divine Punishment",
        skilltwotype: "Cooperation",
        skilltwoprob: 20,
        skilltwodescr: "When deployed Troops does a basic attack, there is a 25% chance of dealing direct damage 1 time (Damage Factor 300) to the target, and increases targets damage received from basic attacks by 20% for 2s.",
        skillawakename: "Heavenly Descent",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Inflicts drect damage in a circular range to up to 5 target Troops once (Damage Factor 825), and increases targets damage received from basic attacks by 10% for 4s.",
        talentonename: "Godly Wrath",
        talentonetype: "Passive",
        talentonedescr: "Triggers when entering battle, increases trigger chance of deployed Troops Cooperation Skills by 6% for 30s.",
        talenttwoname: "Divine Blessing",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troop performs a basic attack, there is a 20% chance to heal their Lightly Wounded units (heal Factor 450).",
        talentthreename: "Divine Punishment",
        talentthreetype: "Cooperation",
        talentthreedescr: "Increases deployed Troops Basic attack Damage by 20%. If the Troops are Bleeding, there is a 20% chance to deal 1 direct damage to the target during a basic attack (Damage Factor 500).",
        id: 5
    },
    {
        name: "Bjorn",
        skillonename: "Splitting Blades",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance(s) of direct damage (Damage Factor 1700) to the target, Slowing them down and reducing their March Speed by 15% for 3s. At the same time, increases infantry attack by 10% for 3s.",
        skilltwoname: "Crippling Pursuit",
        skilltwotype: "Cooperation",
        skilltwoprob: 20,
        skilltwodescr: "When the deployed Troop performs a basic attack, there is a 20% chance of dealing 1 instance of direct damage to the target (Damage Factor 500). If the target is Slowed, another instance of direct damage (Damage Factor 250) will be dealt.",
        skillawakename: "Lethal Fracture",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance(s) of direct damage (Damage Factor 2000) to the target, Slowing them down and reducing their March Speed by 20% for 3s. At the same time, increases infantry attack by 15% for 3s.",
        talentonename: "Trained Up",
        talentonetype: "Cooperation",
        talentonedescr: "When deployed Troop performs a basic attack, there is a 25% chance to deal direct damage 1 time (Damage Factor 300) to the target. Damage has 30% chance to cause target to be Slowed, reducing March Speed by 25% for 2s.",
        talenttwoname: "Undefeated",
        talentwotype: "Passive",
        talenttwodescr: "Increases deployed Troops Cooperation Skill Damage by 15%",
        talentthreename: "Fatal Bleeding",
        talentthreetype: "Command",
        talentthreedescr: "Every 6s inflict Bleed on the target, dealing coninuous damage every second (Damage Factor 600) for 2s.",
        id: 6
    },
    {
        name: "Hobert",
        skillonename: "Goundshaker",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals direct damage 1 time to the target (Damage Factor 1000), Dispels 1 random Buff from the target and Purifies 1 Debuff from deployed Troop. Deployed Troop also gains a Shield (Shield Factor 300) for 2s.",
        skilltwoname: "Berserk Fury",
        skilltwotype: "Passive",
        skilltwoprob: 100,
        skilltwodescr: "For every 6% of Health that the deployed Troop loses, you receive 3% Rage Gain and 12% Basic Attack Damage bonus. This effect Stacks up to 5 times. (This effect cannot be cleared).",
        skillawakename: "Brutal Blow",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals direct damage 1 time to the target (Damage Factor 1200), Dispels 2 random Buffs from the target and Purifies 1 Debuff from deployed Troop. Deployed Troop also gains a Shield (Shield Factor 400) for 2s.",
        talentonename: "Bold Shieldaxe",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed troops Basic attack Damage by 35%.",
        talenttwoname: "Fearless Pursuit",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troop performs a basic attack, There is a 20% chance to deal damage 1 time (Damage Factor 350). If the target is suffering from a Debuff, the damage will be increasd (Damage Factor 700).",
        talentthreename: "Steadfast Armor",
        talentthreetype: "Cooperation",
        talentthreedescr: "When deployed Troops use a basic attack, there is a 20% chance to grant the Troops a damage reduction effect, reducing the damage taken by 28% for 1s. Also causes the target to be Slowed by 10% for 2s.",
        id: 7
    },
    {
        name: "Vali",
        skillonename: "Deadly Slash",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals direct damage (Damage Factor 1385) to up to 3 targets within a circular range. If the target is inflicted with Bleed, deals diect damage (Damage Factor 435) to the target.",
        skilltwoname: "Curse of the Frost",
        skilltwotype: "Cooperation",
        skilltwoprob: 100,
        skilltwodescr: "Reduces deployed Troops Counterattack Damage by 15%. When deployed Troop casts an Active Skill, deals direct damage 1 time on the target (Damage Factor 600). If the target is inflicted with Slow, this damage is increased (Damage Factor 900), and deployed Troop gains a shield (Shield Factor 500) that lasts for 2 rounds.",
        skillawakename: "Frostblade",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals direct damage (Damage Factor 1600) to up to 4 targets within a circular range. If the target is inflicted with Bleed, deals diect damage (Damage Factor 500) to the target. If own deployed Troop is inflicted with Retribution, they will receive healing (Heal Factor 1200).",
        talentonename: "Icy Edge",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Basic Attack Damage by 30%, and Bleed Damage dealt by 10%",
        talenttwoname: "Ice Cleave",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troop performs a basic attack, There is a 10% chance to inflict Bleed on the target. Bleeding enemies will take continuous damage every second (Damage Factor 700) for 2s. There is a 10% chance to inflict Silence ont the target for 2s. There is a 10% chance to inflict Slow on the target, decreasing their March Speed by 30% for 2s. (values need confirming)",
        talentthreename: "An Eye for an Eye",
        talentthreetype: "Cooperation",
        talentthreedescr: "When deployed Troop performs a basic attack, there is a 20% chance to grant them Retribution, increasing Retribution Rate by 25% for 2s. If the target is inflicted with Bleed, Retribution Rate increases to 50% and an additional direct damage (Damage Factor 750) is dealt to the target.",
        id: 8
    },
    {
        name: "Sephina",
        skillonename: "Night Ravens Raid",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 1360) to the target. If the target is inflicted with Slow, they will be inflicted with Bleed. Bleeding enemies will take continuous damage every second (Damage Factor 240) for 2s",
        skilltwoname: "Darkmoon Elegy",
        skilltwotype: "Cooperation",
        skilltwoprob: "20",
        skilltwodescr: "When deployed Troop performs a basic attack, there is a 20 % chance to deal direct damage 1 time to the target (Damage Factor 500). Also clears 1 debuff from own deployed Troop. When dealing damage, if the target is inflicted with Silence, there is a 100 % chance to deal direct damage 1 time to the target (Damage Factor 1,000), and dispel 1 buff on the target.",
        skillawakename: "Moonlit Strike",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,700) to the target, and inflicts them with Bleed. If the target is inflicted with Slow, they will be inflicted with Bleed. Bleeding enemies will take continuous damage every second (Damage Factor 300) for 2s. If the target is inflicted with Silence, deals an additional instance of direct damage to the target (Damage Factor 1,200).",
        talentonename: "Raven Feather Blade",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Basic Attack Damage by 30%. When performing a basic attack, if the target is inflicted with Bleed, there is a 25% chance for your own Troop to receive healing (Heal Factor 250).",
        talenttwoname: "Death Ravens Shadow",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troop casts an Active Skill, deals direct damage 1 time on the target (Damage Factor 400). If deployed Troop has more units than the target, the target will be inflicted with Bleed. Bleeding enemies will take continuous damage every second (Damage Factor 200) for 2s. If deployed Troop has fewer units than the target, deals direct damage 1 time on the target (Damage Factor 425), and inflicts Slow on the the target, decreasing their March Speed by 30% for 3s.",
        talentthreename: "Ominous Raven Feather",
        talentthreetype: "Cooperation",
        talentthreedescr: "When deployed Troop performs a basic attack, there is a chance of 15% to deal direct damage 1 time to the target (Damage Factor 325). There is a 15% chance to inflict Silence on the target for 1s, a 15% chance to heal own Troop (Heal Factor 325), and a 25% chance to grant own Troop with Retribution, increasing Retribution Rate by 50% for 2s.",
        id: 9
    },
    {
        name: "Margit",
        skillonename: "Fierce battle at Sea",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of single-target damage (Damage Factor 1,050) to the target and inflicts them with Bleed. Bleeding enemies will take continuous damage every second (Damage Factor 400) for 2s.",
        skilltwoname: "Ride the Waves",
        skilltwotype: "Cooperation",
        skilltwoprob: 100,
        skilltwodescr: "Increases deployed Troops Basic Attack Damage by 20 %. When performing a basic attack, if the target is Slowed, there is a 50 % chance for your own Troop to increase their Basic Attack Damage by 100% for 2s.",
        skillawakename: "Raging Tide",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of single-target damage (Damage Factor 1,600) to the target and inflicts them with Bleed. Bleeding enemies will take continuous damage every second (Damage Factor 600) for 2s. Also inflicts target with Slow, reducing their March Speed by 25 % for 4s.",
        talentonename: "Cutting Blade",
        talentonetype: "Passive",
        talentonedescr: "Increases Bleed Damage by 25%",
        talenttwoname: "Thirst for Blood",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troops perform a basic attack, if the target is Bleeding, there is a 35% chance for Lightly Wounded units from your own Troops to heal 1 time (Heal Factor 800).",
        talentthreename: "Seas Grace",
        talentthreetype: "Command",
        talentthreedescr: "Every 6s, Purifies own Troop of 1 Debuff, and randomly inflicts one of the following effects to the target: Bleed, which causes continuous damage every second (Damage Factor 1000) for 2s, or Slow: which reduces March Speed by 30% for 2s.",
        id: 10
    },
    {
        name: "Cecia",
        skillonename: "Carnage",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 950) to the target and increases their Basic Attack Damage received by 25 % for 3s.",
        skilltwoname: "All In",
        skilltwotype: "Passive",
        skilltwoprob: 100,
        skilltwodescr: "Increase Attack by 30% and reduce Defense by 10%",
        skillawakename: "Fight for Life",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,250) to the target and increases their Basic Attack Damage received by 30 % for 3s.",
        talentonename: "Death Fight",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Basic Attack Damage by 20%",
        talenttwoname: "Mad Arsonist",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troops use an Active Skill, there is a 50% chance to deal direct damage 1 time (Damage Factor 750) to the target.",
        talentthreename: "Power War Axe",
        talentthreetype: "Cooperation",
        talentthreedescr: "When your deployed Troop does basic attacks, there is a 15 % chance to deal an additional instance of damage (Damage Factor 750).",
        id: 11
    },
    {
        name: "Rosky",
        skillonename: "Spirit Ship",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 2000) to the target and reduces their Defense by 20% for 4s",
        skilltwoname: "Flurry",
        skilltwotype: "Counterattack",
        skilltwoprob: 20,
        skilltwodescr: "When deployed Troops receive a basic attack, there is a 20 % chance to deal direct damage 1 time (Damage Factor 700) to the target. Also increases Counterattack Skill Damage of deployed Troops by 50% for 2 seconds.",
        skillawakename: "Spirit Battleship",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 2800) to the target and reduces their Defense by 30% for 4s.",
        talentonename: "Blade Wielder",
        talentonetype: "Passive",
        talentonedescr: "Triggers when entering battle, increases deployed Troops Counterattack Damage by 150% for 60s",
        talenttwoname: "Maniacal",
        talentwotype: "Counterattack",
        talenttwodescr: "When deployed Troops counterattack, there is a 20 % chance to heal Lightly Wounded Troops (Heal Factor 350) every second for 2 seconds.",
        talentthreename: "Pirate Tricks",
        talentthreetype: "Counterattack",
        talentthreedescr: "When deployed Troops take Active Skill Damage, there is a 50% chance to grant them a shield (Shield Factor 570) for 3 seconds.",
        id: 12
    },
    {
        name: "Helgar",
        skillonename: "Spear of Judgement",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 900) to up to 3 targets within an arc. If the deployed Troop has more than 5 stacks of Judgment Mark, deals an additional instance of damage (Damage Factor 720).",
        skilltwoname: "Judgments Fury",
        skilltwotype: "Passive",
        skilltwoprob: 100,
        skilltwodescr: "When taking Basic Attack Damage, the deployed Troop will receive 1 stack of Judgment Mark. When there are 20 stacks, it will deal direct damage (Damage Factor 1,150) 1 time to target, all the Marks are removed, and Troops Counterattack Damage will be increased by 45% for 2s. (Judgment Mark cannot be removed by the enemy)",
        skillawakename: "Ruling Trial",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,000) to up to 4 targets in a circular range. If the target has less than 20 % Troops, they will receive greater damage (Damage Factor 1,500). If the target has more than 5 stacks of Judgment Mark, they will take 1 additional instance of damage (Damage Factor 800).",
        talentonename: "Saintly Guardian",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Shield by 35%",
        talenttwoname: "War Blessings",
        talentwotype: "Passive",
        talenttwodescr: "When deployed Troop receives healing, there is a 50 % chance to gain a shield (Shield Factor 500) for 2 seconds and obtain 1 Judgment Mark(s) (up to 1 Mark stacks every 1 seconds. Judgment Mark cannot be removed by the enemy).",
        talentthreename: "Judgement Mark",
        talentthreetype: "Counterattack",
        talentthreedescr: "When deployed Troop counterattacks, there is a 50% chance to deal direct damage 1 time to the target (Damage Factor 350) and obtain 3 stacks of Judgment Mark (this Mark effect triggers up to 3 times every 1 seconds. Judgment Marks cannot be removed by the enemy).",
        id: 13
    },
    {
        name: "Laird",
        skillonename: "Divine Destruction",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 800) to up to 3 targets within an arc and increases Pikeman Attack by 15% for 3s.",
        skilltwoname: "Flame Guardian",
        skilltwotype: "Counterattack",
        skilltwoprob: 20,
        skilltwodescr: "When deployed Troops counterattack, there is a 20% chance to deal direct damage 1 time (Damage Factor 250) to the target. Damage has a 50% chance to grant deployed Troops a shield (Shield Factor 400) for 2 seconds.",
        skillawakename: "Sacred Blade",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,400) to up to 3 targets in a circular range and increases Pikeman Attack by 20% for 3s.",
        talentonename: "Holy Shield",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Shield by 25%",
        talenttwoname: "Sacred Counter",
        talentwotype: "Counterattack",
        talenttwodescr: "When deployed Troops are targeted by a basic attack, there is a 20% chance of dealing direct damage 1 time (Damage Factor 600) to the target.",
        talentthreename: "Divine Resistance",
        talentthreetype: "Passive",
        talentthreedescr: "Reduces Basic Attack Damage taken by deployed Trops by 40 % and increases Counterattack damage by 40 %",
        id: 14
    },
    {
        name: "Leif",
        skillonename: "Chasing Waves",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deal direct damage 1 time (Damage Factor 1,050) to the target and grant deployed Troops a shield (Shield Factor 420) for 2 seconds.",
        skilltwoname: "Planned Attack",
        skilltwotype: "Counterattack",
        skilltwoprob: 15,
        skilltwodescr: "When deployed Troops counterattack, there is a 15% chance to deal direct damage 2 times to the target (Damage Factor 300,420).",
        skillawakename: "Sharp Pursuit",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deal direct damage 1 time (Damage Factor 1,500) to the target and grant deployed Troops a shield (Shield Factor 600) for 2 seconds.",
        talentonename: "Blade Counter",
        talentonetype: "Counterattack",
        talentonedescr: "When deployed Troop counterattacks, there is a 15% chance to increase Counterattack Damage by 30% for 4 seconds. Also, there is a 25% chance to gain Immunity to Broken Blade for 4 seconds.",
        talenttwoname: "Shield of Resistance",
        talentwotype: "Passive",
        talenttwodescr: "When deployed Troops receive healing, there is a 20% chance to grant them a shield (Shield Factor 950) for 2 seconds.",
        talentthreename: "Revenge Echo",
        talentthreetype: "Counterattack",
        talentthreedescr: "When deployed Troops receive a basic attack, there is a 25% chance to deal direct damage 1 time (Damage Factor 650) to the target. When deployed Troops deal damage while they have a shield, increases their Counterattack Damage by 30% for 2 seconds",
        id: 15
    },
    {
        name: "Sigurd",
        skillonename: "Violent Tendencies",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals direct damage 1 time (Damage Factor 1,400) to the target. Also increases counterattack skill damage of deployed Troops by 12% for 2 seconds.",
        skilltwoname: "Snake Eyes",
        skilltwotype: "Passive",
        skilltwoprob: 25,
        skilltwodescr: "When deployed Troop is shielded, there is a 25% chance to deal direct damage 1 time to the target (Damage Factor 500), and a 20% chance to inflict Broken Blade on the target for 2 seconds.",
        skillawakename: "Snakes Frenzy",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals direct damage 1 time (Damage Factor 1,600) to the target. Also increases counterattack skill damage of deployed Troops by 15% for 2 seconds.",
        talentonename: "Fiery Snake Spirit",
        talentonetype: "Passive",
        talentonedescr: "Increases Main Commander active skill Damage by 30%",
        talenttwoname: "Serpents Rage",
        talentwotype: "Command",
        talenttwodescr: "Deals direct damage 1 time (Damage Factor 900) to the target every 9 seconds.",
        talentthreename: "Full Focus",
        talentthreetype: "Passive",
        talentthreedescr: "When deployed Troops receive Healing, there is a 35% chance to deal direct damage 1 time (Damage Factor 700) to the target.",
        id: 16
    },
    {
        name: "Rolfe",
        skillonename: "Fatal Rhythm",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deal direct damage 1 time (Damage Factor 1,665) to up to 4 targets within a circular area, and inflict targets with Broken Blade for 2 seconds.",
        skilltwoname: "Inspiration Arrives",
        skilltwotype: "Passive",
        skilltwoprob: 50,
        skilltwodescr: "When deployed Troops are healed, there is a 50% chance to deal direct damage 1 time (Damage Factor 400) to target, and increase deployed Troops counterattack damage by 100% for 1 seconds. Triggers up to 1 time every 1 seconds.",
        skillawakename: "Indomitable Spirit",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deal direct damage 1 time (amage Factor 2000) to up to 4 targets within a circular area, and inflict targets with Broken Blade for 2 seconds. If the target Troops units are below 50%, they will receive even higher damage (Damage Factor 2,500).",
        talentonename: "Assassination Raid",
        talentonetype: "Counterattack",
        talentonedescr: "When deployed Troop receives Active Skill Damage, deal direct damage 1 time (Damage Factor 400) to target. If target is inflicted with Broken Blade, deployed Troop receives healing 1 time (Heal Factor 650).",
        talenttwoname: "Scale Armor Shield",
        talentwotype: "Counterattack",
        talenttwodescr: "When deployed Troops counterattack, there is a 25% chance to grant them a shield (Shield Factor 660) for 2 seconds. Triggers up to 1 time every 2 seconds.",
        talentthreename: "Feigned Death Strike",
        talentthreetype: "Counterattack",
        talentthreedescr: "When deployed Troop receives a basic attack, there is a 25% chance to deal direct damage 1 time (Damage Factor 650) to target. If target is inflicted with Broken Blade, deployed Troop receives healing 1 time (Heal Factor 650). Triggers up to 1 time every 2 seconds.",
        id: 17
    },
    {
        name: "Naya",
        skillonename: "Icebreaker Strike",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deal direct damage 1 time (Damage Factor 1600) to the target and grant deployed Troops a shield (Shield Factor 600) for 2 seconds",
        skilltwoname: "Hunting Instinct",
        skilltwotype: "Counterattack",
        skilltwoprob: 20,
        skilltwodescr: "When deployed Troop launches a counterattack, there is a 20% chance of dealing direct damage (Damage Factor 600) 1 time to target. If deployed Troop is shielded, this damage is increased (Damage Factor 1,000), and the target is inflicted with Broken Blade for 1 seconds. Triggers up to 1 time every 3 seconds.",
        skillawakename: "Blizzard Spear",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deal direct damage 1 time (Damage Factor 2000) to the target and grant deployed Troops a shield (Shield Factor 900). If the target is inflicted with Broken Blade, the shield is enhanced (Shield Factor 1200) and lasts for 2 seconds.",
        talentonename: "Forcefull Ambush",
        talentonetype: "Passive",
        talentonedescr: "When deployed Troops are healed, counterattack damage is increased by 25% for 1 seconds. There is an additional 20% chance for deployed Troops to gain a shield (Shield Factor 650) for 2 seconds. Triggers up to 1 time every 3 seconds.",
        talenttwoname: "Trapped Beast Struggle",
        talentwotype: "Counterattack",
        talenttwodescr: "When deployed Troop receives a basic attack, there is a 20% chance of dealing direct damage 1 time (Damage Factor 600) to target. If the target is inflicted with Broken Blade, this damage is increased (Damage Factor 1000). Triggers up to 1 time every 3 seconds.",
        talentthreename: "Bear Spirit Protection",
        talentthreetype: "Counterattack",
        talentthreedescr: "When deployed Troop receives healing, there is a 50% chance to deal direct damage 1 time (Damage Factor 500) to target, and inflict target with Broken Blade for 1 seconds. Triggers up to 1 time every 1 seconds.",
        id: 18
    },
    {
        name: "Yvette",
        skillonename: "Mending Light",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Heals Lightly Wounded units (Heal Factor 850) of up to 3 ally Troops in a circular range, and increases Counterattack Damage of the deployed Troop by 20% for 5s.",
        skilltwoname: "Sanctity of Life",
        skilltwotype: "Passive",
        skilltwoprob: 20,
        skilltwodescr: "There is a 20% chance every 1 s to heal the Lightly Wounded units in the deployed Troop once (Heal Factor 500), and a 20% chance to increase the Active Skill Damage of the Secondary Commander of the deployed Troop by 20% for 3s.",
        skillawakename: "Vital Blessing",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Heals Lightly Wounded units (Heal Factor 1,250) of up to 5 ally Troops in a circular range, and increases Counterattack Damage of the deployed Troop by 30% for 5s.",
        talentonename: "Healing Chords",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Healing Received by 20%",
        talenttwoname: "Healing Hymn",
        talentwotype: "Passive",
        talenttwodescr: "When your deployed Troops receive healing, there is a 25% chance to deal 1 instance of damage (Damage Factor 800) to the target.",
        talentthreename: "Horn of Countering",
        talentthreetype: "Counterattack",
        talentthreedescr: "When your deployed Troops deal counterattacks, there is a 20% chance to deal additional damage (Damage Factor 900).",
        id: 19
    },
    {
        name: "Wooder",
        skillonename: "Defensive Attack",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 300) to up to 3 targets within an arc and fains a Shield for 3s (Shield Factor 500)",
        skilltwoname: "Ready to Pounce",
        skilltwotype: "Passive",
        skilltwoprob: 100,
        skilltwodescr: "Each time Active Skill Damage is received from the target, increases Counterattack Damage by 100% for 2s",
        skillawakename: "Paralyzing Teror",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 450) to up to 3 targets within an arc and fains a Shield for 3s (Shield Factor 700)",
        talentonename: "Massive Shield",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Shield by 15%",
        talenttwoname: "Bold Charge",
        talentwotype: "Counterattack",
        talenttwodescr: "When your deployed Troops deal counterattacks, there is a 20% chance to deal additional damage (Damage Factor 250)",
        talentthreename: "Specialized Attack",
        talentthreetype: "Counterattack",
        talentthreedescr: "When deployed Troops receive Active Skill Damage, there is a 50% chance to deal direct damage 1 time (Damage Factor 1,250) to the target.",
        id: 20
    },
    {
        name: "Verdandi",
        skillonename: "Diversion Shot",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 1,400) to the target and inflicts them with Burning. Burning enemies will take continuous damage every second (Damage Factor 200) for 2s.",
        skilltwoname: "Rapid Fire",
        skilltwotype: "Command",
        skilltwoprob: 100,
        skilltwodescr: "Deals direct damage 1 time (Damage Factor 800) to the target every 9s and deployed Troops gane 50 Rage",
        skillawakename: "Raining Arrows",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,800) to the target and inflicts them with Burning. Burning enemies will take continuous damage every second (Damage Factor 300) for 2s.",
        talentonename: "Hunting Instinct",
        talentonetype: "Passive",
        talentonedescr: "Increases Burn damage by 18%",
        talenttwoname: "Hunting Experience",
        talentwotype: "Command",
        talenttwodescr: "Every 9 seconds, inflict Burning on the target, dealing continuous damage every second (Damage Factor 500) for 2 seconds.",
        talentthreename: "Targeted Strike",
        talentthreetype: "Command",
        talentthreedescr: "Deals direct damage 1 time (Damage Factor 550) to the target every 6 seconds and if the target is Burning, damage dealt is increased (increased to Damage Factor 1100).",
        id: 21
    },
    {
        name: "Freydis",
        skillonename: "Flame Slash",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage to the target (Damage Factor 560) and inflicts them with Burn. Burning enemies will take continuous damage every second (Damage Factor 245) for 4s.",
        skilltwoname: "Blades Judgement",
        skilltwotype: "Command",
        skilltwoprob: 100,
        skilltwodescr: "Deals 1 instance of direct damage to the target every 9 seconds (Damage Factor 240) and inflicts them with Burn. Burning enemies will take continuous damage every second (Damage Factor 240) for 3s.",
        skillawakename: "Desperate Strike",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 800) to the target and inflicts them with Burning. Burning enemies will take continuous damage every second (Damage Factor 350) for 4s.",
        talentonename: "Heroic Blessing",
        talentonetype: "Passive",
        talentonedescr: "Triggers when entering battle, reduces deployed Troops Counterattack Damage by 30% for 30 seconds. After 30 seconds, increases their Burn Damage by 15% (this Buff cannot be removed and will last until the end of the battle).",
        talenttwoname: "Battle Hymn",
        talentwotype: "Passive",
        talenttwodescr: "Deals 1 instance of direct damage (Damage Factor 800) to the target every 9 seconds. When your deployed Troops Rage is lower than the target, they restore 50 Rage.",
        talentthreename: "Flames Judgment",
        talentthreetype: "Passive",
        talentthreedescr: "If the target is Burning, there is a 30% chance for deployed Troops to deal direct damage 1 time (Damage Factor 1000) to the target when triggering a Command Skill.",
        id: 22
    },
    {
        name: "Artur",
        skillonename: "Burning fire",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Inflicts direct damage in a fan shape to up to 3 target Troops once (Damage Factor 900), with a 35 % chance of increasing Burn Damage by 20% for 4s.",
        skilltwoname: "Torment",
        skilltwotype: "Command",
        skilltwoprob: 100,
        skilltwodescr: "Deals direct damage to target Troops every 9s (Damage Factor 700), and inflicts them with Burn. Burning enemies will take continuous damage every second (Damage Factor 350) for 3s.",
        skillawakename: "Incineration",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Inflicts direct damage in a circular shape to up to 3 target Troops once (Damage Factor 1,300), with a 50 % chance of increasing Burn Damage by 30% for 4s.",
        talentonename: "Hellfire Shelter",
        talentonetype: "Passive",
        talentonedescr: "Counterattack Damage taken by deployed Troops is reduced by 40%.",
        talenttwoname: "Pent-Up Anger",
        talentwotype: "Command",
        talenttwodescr: "Every 9 seconds, deployed Troops gain 300 Rage.",
        talentthreename: "Furious Fire",
        talentthreetype: "Command",
        talentthreedescr: "Deals direct damage 1 time (Damage Factor 1100) to the target every 6 seconds.",
        id: 23
    },
    {
        name: "Leandra",
        skillonename: "Jagged Edge",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 900) to the target with a 50 % chance of dealing another instance of damage (Damage Factor 900). Also has a 50 % chance to Poison the target when dealing damage for the first time. Poisoned enemies take 1 instance of damage each second (Damage Factor 360) for 3s.",
        skilltwoname: "Vengeful Fury",
        skilltwotype: "Cooperation",
        skilltwoprob: 20,
        skilltwodescr: "When deployed Troop performs a basic attack, there is a 20 % chance to inflict Burning on the target, dealing continuous damage every second (Damage Factor 200) for 2 seconds. If the target is already Poisoned, deployed Troop gains an additional 100 Rage.",
        skillawakename: "Serrated Flourish",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,400) to the target with a 50 % chance of dealing another instance of damage (Damage Factor 1,400). Also has a 50 % chance to Poison the target when dealing damage for the first time. Poisoned enemies take 1 instance of damage each second (Damage Factor 600) for 3s.",
        talentonename: "Soul Awakening",
        talentonetype: "Passive",
        talentonedescr: "Counterattack Damage taken by deployed Troops is reduced by 45%.",
        talenttwoname: "Flexible Strike",
        talentwotype: "Cooperation",
        talenttwodescr: "If target is Burning, basic attacks have a 25% chance to deal damage 1 time (Damage Factor 500) to the target. If target is not burning, your Troop has a 25% chance to heal 1 time (Heal Factor 500).",
        talentthreename: "Oppertune Strike",
        talentthreetype: "Command",
        talentthreedescr: "Every 6 seconds, inflict Poison on the target, dealing continuous damage every second (Damage Factor 650) for 2 seconds",
        id: 24
    },
    {
        name: "Sasha",
        skillonename: "Entwined Vines",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Inflict Poison on the target, dealing continuous damage (Damage Factor 560) every second for 3s. If Nature Mark of deployed Troop reaches 5 stacks, deal additional direct damage (Damage Factor 720).",
        skilltwoname: "Nature Blessing",
        skilltwotype: "Command",
        skilltwoprob: 100,
        skilltwodescr: "Every 9s, grant deployed Troop 1 stacks of Nature Mark and 1 time healing (Heal Factor 700). When Nature Mark reaches 5 stacks, deal direct damage (Damage Factor 700) once to the target. When Nature Mark reaches 15 stacks, deployed Troops evasion increases by 100 % for 2s, and the Mark is removed.",
        skillawakename: "Froral Burial",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Inflict Poison on the target, dealing continuous damage (Damage Factor 700) every second for 3s. If Nature Mark of deployed Troop reaches 5 stacks, deal additional direct damage (Damage Factor 900) once. If Nature Mark of deployed Troop reaches 10 stacks, trigger Life Drain, converting 50% of the damage dealt to heal deployed Troop.",
        talentonename: "Forest Force",
        talentonetype: "Passive",
        talentonedescr: "The active skill damage of deployed Troop is increased by 20%. And Poison damage is increased by 20%.",
        talenttwoname: "Natures Killer",
        talentwotype: "Command",
        talenttwodescr: "Every 6s, grant 1 stacks of Nature Mark to deployed Troop. When Nature Mark reaches 5 stacks, inflict Poison on the target, dealing continuous damage (Damage Factor 250) per second for 3s. When Nature Mark reaches 10 stacks, inflict Burning on the target, dealing continuous damage (Damage Factor 400) per second for 3s.",
        talentthreename: "Life Cycle",
        talentthreetype: "Cooperation",
        talentthreedescr: "When deployed Troop casts an active skill, deployed Troop gains 2 stacks of Nature Mark. If the target is inflicted with Burning, deal direct damage (Damage Factor 900) once to target. If the target is inflicted with Poison, deployed Troop receives healing (Heal Factor 900) once.",
        id: 25
    },
    {
        name: "Alf",
        skillonename: "Rapid Assault",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deal direct damage (Damage Factor 1,120) once to the target. There is a 32 % chance to trigger Burst once, inflict Burning on tarnet and deal continuous damage (Damage Factor 480) every second for 3s.",
        skilltwoname: "Hugginns Slingshot",
        skilltwotype: "Cooperation",
        skilltwoprob: 20,
        skilltwodescr: "Deployed Troops basic attacks have a 20% chance to deal direct damage (Damage Factor 400) once to the target. If the target is inflicted with Burning, this damage is increased (Damage Factor 800).",
        skillawakename: "Chain Meteor",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deal direct damage (Damage Factor 1,400) once to the target. There is a 40 % chance to trigger Burst once, inflict Burning on target and deal continuous damage (Damage Factor 600) every second for 3s. There is a 40 % chance to launch an additional Poison Marble, inflict Poison on the target and deal continuous damage (Damage Factor 600) every second for 3s.",
        talentonename: "Fiery Poison Bullet",
        talentonetype: "Passive",
        talentonedescr: "Increase Burning damage by 15%, and increase Poison damage by 15%",
        talenttwoname: "Fiery Poison Bomb",
        talentwotype: "Command",
        talenttwodescr: "Inflict target with Poison every 9s, dealing continuous damage (Damage Factor 575) per second for 2s, and granting 200 Rage to deployed Troop.",
        talentthreename: "Agile Missile",
        talentthreetype: "Command",
        talentthreedescr: "Inflict target with Burning every 6s, dealing continuous damage (Damage Factor 450) every second for 2s. If the target is inflicted with Poison, there is a 30 % chance to increase deployed Troops evasion by 100% for 1s.",
        id: 26
    },
    {
        name: "Yulmi",
        skillonename: "Deathly Scythe",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Inflicts direct damage in a fan shape to up to 3 target Troops once (Damage Factor 1,350), and decreases target Troops Health by 8 % for 2s.",
        skilltwoname: "Plague",
        skilltwotype: "Command",
        skilltwoprob: 100,
        skilltwodescr: "Every 9 seconds, inflict Poison on the target, dealing continuous damage every second (Damage Factor 500) for 3 seconds. If the target is already Poisoned, damage dealt to the target will be increased by 20% for 3 seconds.",
        skillawakename: "Undead Harvest",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Inflicts direct damage in a fan shape to up to 3 target Troops once (Damage Factor 1,800), and decreases target Troops Health by 10 % for 2s.",
        talentonename: "Dreadful Curse",
        talentonetype: "Passive",
        talentonedescr: "Increases Poison Damage by 25%",
        talenttwoname: "High Fighting Spirit",
        talentwotype: "Command",
        talenttwodescr: "Deals direct damage 1 time (Damage Factor 1300) to the target every 9 seconds and increases Active Skill Damage of your deployed Troops by 20% for 5 seconds.",
        talentthreename: "Low Whispers",
        talentthreetype: "Command",
        talentthreedescr: "Every 6 seconds, your deployed Troops gain a damage reduction buff, reducing damage taken by 30% for 2 seconds. If the target is Burning, your deployed Troops also gain 180 Rage.",
        id: 27
    },
    {
        name: "Olena",
        skillonename: "High Focus",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Inflict direct damage to target once (Damage Factor 900), and recover 50 Rage every second for all deployed Troops for 2s. If target is Burning. deployed Troops will gain 100 Rage after 1 round.",
        skilltwoname: "Enchanted Arrow",
        skilltwotype: "Cooperation",
        skilltwoprob: 35,
        skilltwodescr: "When the active skill is cast, it has a 35 % chance to burn target Troops, inflicting 600 damage per second (Damage Factor 600) for 2s",
        skillawakename: "Concentration",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Inflict direct damage to target once (Damage Factor 1,250), and recover 100 Rage every second for all deployed Troops for 2s. If target is Burning, deployed Troops will gain 200 Rage after 1 round.",
        talentonename: "Scorching Arrow",
        talentonetype: "Passive",
        talentonedescr: "Increases Burn Damage by 15%.",
        talenttwoname: "Multi-Shot Arrow",
        talentwotype: "Command",
        talenttwodescr: "When your deployed Troops receive active Skill Damage, ther is a 50% chance of dealing 1 instance of direct damage (Damage Factor 750) to the target",
        talentthreename: "Poised Shot",
        talentthreetype: "Cooperation",
        talentthreedescr: "When deployed Troops use an Active skill, deal direct damage 1 time (Damage Factor 575) to the target, with a 15% chance to reduce targets Rage by 150",
        id: 28
    },
    {
        name: "Ragnar",
        skillonename: "Road of Conquest",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Increases the Attack, Defense, and Health of up to 3 ally Troops in a circular range by 12 % for 4s. When acting as a Main Commander, 1 instance of direct damage (Damage Factor 900) will be dealt to up to 3 target units in a circular range. The amount of direct damage dealt to each unit will be reduced by 10 % for each target previously hit.",
        skilltwoname: "Unyielding Will",
        skilltwotype: "Counterattack",
        skilltwoprob: 15,
        skilltwodescr: "When taking Basic Attack Damage, increases the Active Skill Damage of the Secondary Commander by 20% for 3s, with a 15 % chance of recovering a certain number of Troops (Recovery Factor 800).",
        skillawakename: "Viking Saga",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Increases the Attack, Defense, and Health of up to 3 ally Troops in a circular range by 15 % for 4s. When acting as a Main Commander, 1 instance of direct damage (Damage Factor 1,400) will be dealt to up to 3 targets in a circular range, reducing each targets Attack by 20 % for 4s. The amount of direct damage dealt to each unit will be reduced by 10 % for each target previously hit.",
        talentonename: "Dragons Blood",
        talentonetype: "Passive",
        talentonedescr: "Decreases witing time of Rallied Troops by 60s, and increases Rallied Troops Defense by 5%",
        talenttwoname: "Rock Solid",
        talentwotype: "Passive",
        talenttwodescr: "Increases deployed Troops Defense by 9%",
        talentthreename: "Born King",
        talentthreetype: "Passive",
        talentthreedescr: "Increases Rallied Troops March Speed by 10%, and increases Rallied Troops Capacity by 15%",
        id: 29
    },
    {
        name: "Ivana",
        skillonename: "Wordless",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Inflicts direct damage in a circular area to up to 3 target Troops 1 time(s) (Damage Factor 600), and decreases targets Rage by 40, with a 50 % chance to Silence target (unable to cast active skills) for 1s.",
        skilltwoname: "Threatening Blade",
        skilltwotype: "Passive",
        skilltwoprob: 30,
        skilltwodescr: "If deployed Troops are greater than target Troops, basic attacks have a 30 % chance to inflict direct damage to target once (Damage Factor 253). If deployed Troops are less than target Troops, basic attacks have a 30 % chance of increasing deployed Troops defense by 10 % for 5s.",
        skillawakename: "Intimidation",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Inflicts direct damage in a circular area to up to 3 target Troops 2 time(s) (Damage Factor 300/Damage Factor 600), and decreases targets Rage by 50, with a 50 % chance to Silence target (unable to cast active skills) for 2s.",
        talentonename: "Power of Silence",
        talentonetype: "Passive",
        talentonedescr: "When target Troops are Silenced, there is a 50% chance to reduce target Troops Rage by 125",
        talenttwoname: "Combat Focus",
        talentwotype: "Command",
        talenttwodescr: "Deals direct damage 1 time (Damage Factor 1000) to the target every 9 seconds.",
        talentthreename: "Time Crunch",
        talentthreetype: "Passive",
        talentthreedescr: "Increases Rallied Troops March Speed by 8%, and increases Rallied Troops Capacity by 10%",
        id: 30
    },
    {
        name: "Aethelflaed",
        skillonename: "Resonating Bowstring",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 800) in a fan shape to the 3 targets and reduces their Basic Attack Damage dealt by 25 % for 3 seconds.",
        skilltwoname: "Heartstrike Arrow",
        skilltwotype: "Command",
        skilltwoprob: 100,
        skilltwodescr: "Deals 1 instance of direct damage (Damage Factor 650) to the target every 9 seconds and restores 50 Rage to deployed Troops.",
        skillawakename: "Pierce Through",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,200) in a fan shape to the 3 targets and reduces their Basic Attack Damage dealt by 30 % for 3 seconds.",
        talentonename: "Valuable Experience",
        talentonetype: "Passive",
        talentonedescr: "Increases EXP gained by deployed Troops by 32% when they defeat Niflungs and other neutral units.",
        talenttwoname: "Vicory Within Reach",
        talentwotype: "Passive",
        talenttwodescr: "Increases deployed Troops Damage against Niflungs and other neutral units by 30%.",
        talentthreename: "Trap Maker",
        talentthreetype: "Passive",
        talentthreedescr: "Beast Pen Trap Point Basic Recovery Value increased by 25 per minute (This Talent can be boosted by Beast Taming Workers).",
        id: 31
    },
    {
        name: "Leidolf",
        skillonename: "Herald",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 450) to up to 3 targets in a circular range, and heals Lightly Wounded units in the Troop once (Heal Factor 225).",
        skilltwoname: "Armor of Twilight",
        skilltwotype: "Passive",
        skilltwoprob: 25,
        skilltwodescr: "When the deployed Troops take damage from basic attacks, there is a 25% chance to increase Defense by 30% for 2s.",
        skillawakename: "Death Rites",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 600) to up to 4 targets in a circular range, and heals Lightly Wounded units in the Troop once (Heal Factor 300).",
        talentonename: "Valuable Experience",
        talentonetype: "Passive",
        talentonedescr: "Increases EXP gained by deployed Troops by 26% when they defeat Niflungs and other neutral units.",
        talenttwoname: "Standby",
        talentwotype: "Passive",
        talenttwodescr: "Increases deployed Troops damage against Niflungs and other neutral units by 15%",
        talentthreename: "Pioneer Will",
        talentthreetype: "Passive",
        talentthreedescr: "Increases deployed Troops Damage against Niflungs and other neutral units by 20%",
        id: 32
    },
    {
        name: "Gunnar",
        skillonename: "Piercing Thrust",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 1440) to the target and inflicts them with Lacerate dealing continuous damage every second (Damage Factor 400) for 2s.",
        skilltwoname: "Bloody Mad",
        skilltwotype: "Counterattack",
        skilltwoprob: "35",
        skilltwodescr: "When deployed Troop is healed, there is a 35% chance to inflict Lacerate on the tagret Troop, dealing continuous damage every second (Damage Factor 200) for 2s, and a 35% chance to grant own Troop a shield (Shield Factor 400) for 2s. Triggers up to 1 time every 1s",
        skillawakename: "One Stroke One Kill",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1800) to the target and inflicts them with Lacerate dealing continuous damage every second (Damage Factor 500) for 2s. If your own Troop is shielded, inflict Broken Blade on the target Troop for 3s.",
        talentonename: "High Tide Hunt",
        talentonetype: "Counterattack",
        talentonedescr: "Deployed Troops damage dealt from Lacerate increases by 15 %. When deployed Troop counterattacks, there is a 20 % chance to reduce your own Troops damage received by 30 % for 1s. There is a 20 % chance to heal your own Troop (Heal Factor 250). Triggers up to 1 time every 3s.",
        talenttwoname: "Fierce Fighting Spirit",
        talentwotype: "Counterattack",
        talenttwodescr: "When deployed Troop is healed, there is a 60 % chance to deal 1 instance of direct damage (Damage Factor 300) to target Troop. When dealing damage, if the target Troop is inflicted with Lacerate, also inflicts Broken Blade on the target Troop for 1s. Triggers up to 1 time every 1s.",
        talentthreename: "Deadly Strike",
        talentthreetype: "Counterattack",
        talentthreedescr: "When deployed Troop receives Active Skill Damage, deals 1 instance of direct damage (Damage Factor 650) to the target Troop, randomly dispels one buff from the target Troop, and grants your own Troop a shield (Shield Factor 650) for 2s. Triggers up to 1 time every is.",
        id: 33
    },
    {
        name: "Hilda",
        skillonename: "Lethal Smash",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage to the target Troop (Damage Factor 1600), and grants a shield to your own Troop (Shield Factor 400) for 2s.",
        skilltwoname: "Boiling Fighting Spirit",
        skilltwotype: "Counterattack",
        skilltwoprob: "20",
        skilltwodescr: "When deployed Troop launches a counterattack, there is a 20 % chance of dealing 1 instance of direct damage (Damage Factor 400) to the target Troop. When dealing damage, if your own Troop is shielded, the target Troop will be inflicted with Lacerate, dealing continuous damage every second (Damage Factor 300) for 3s. Triggers up to 1 time every 3s.",
        skillawakename: "Shatter",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage to the target Troop (Damage Factor 2,000), and grants a shield to your own Troop (Shield Factor 500) for 2s. If the target Troop is inflicted with Lacerate, heals your own Troop (Heal Factor 400) for 2s.",
        talentonename: "Hammer And Shield",
        talentonetype: "Counterattack",
        talentonedescr: "Deployed Troop's shield increases by 15 % and damage dealt from Lacerate increases by 15 %. When deployed Troop launches a counterattack, there is a 20 % chance of dealing 1 instance of direct damage (Damage Factor 200) to the target Troop. Triggers up to 1 time every 3s.",
        talenttwoname: "Savage Physique",
        talentwotype: "Counterattack",
        talenttwodescr: "When deployed Troop receives healing, there is a 35 % chance to deal 1 instance of direct damage (Damage Factor 500) to the target Troop, and randomly Purify 2 debuff from your own Troop. If your own Troop is shielded, immediately restores 150 of their Rage, and increases their Counterattack Damage by 50 % for 1 s. Triggers up to 1 time every 2s.",
        talentthreename: "Berserk Counterattack",
        talentthreetype: "Counterattack",
        talentthreedescr: "When deployed Troop receives a basic attack, there is a 20 % chance to grant your own Troop a shield (Shield Factor 500) for 2s, a 15 % chance to inflict Broken Blade on the target Troop for 2s, and a 20 % chance to inflict Lacerate on the target Troop, dealing continuous damage every second (Damage Factor 300) for 2s. Triggers up to 1 time every 3s.",
        id: 34
    },
    {
        name: "Athelstan",
        skillonename: "Eloquence",
        skillonetype: "Active",
        skilloneprob: "50",
        skillonedescr: "Deals 1 instance of direct damage to the target Troop (Damage Factor 320) and has a 50 % chance to inflict them with Burn. Burning enemies will take continuous damage every second (Damage Factor 60) for 2s.",
        skilltwoname: "Heart of Tolerance",
        skilltwotype: "Command",
        skilltwoprob: 100,
        skilltwodescr: "Every 9s, deals 1 instance of direct damage (Damage Factor ??) to the target Troop, and has a ?? % chance to reduce the target Troops Rage by ??.",
        skillawakename: "Holy Enlightenment",
        skillawaketype: "Active",
        skillawakeprob: 50,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,400) to the target Troop, and has a 50 % chance to inflict them with Burn. Burning enemies will take continuous damage every second (Damage Factor 200) for 3s. There is a 50 % chance to increase the target Troops damage received by 25 % for 3s.",
        talentonename: "Erudite",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Burning damage dealt by 15 % and Poison damage dealt by 10 %",
        talenttwoname: "Strategize",
        talentwotype: "Command",
        talenttwodescr: "Every 9s, increases deployed Troops Command Skill damage dealt by 35 % for 3s. If the target Troop is inflicted with Burning, there is a 50 % chance for deployed Troop to receive healing (Heal Factor 600).",
        talentthreename: "Adaptable to Changes",
        talentthreetype: "Command",
        talentthreedescr: "Every 6s, deals 1 instance of direct damage (Damage Factor 650) to the target Troop, and has a 50 % chance to inflict the target Troop with Poison. Poisoned enemies take continuous damage every second (Damage Factor 250) for 2s.",
        id: 35
    },
    {
        name: "Heahmund",
        skillonename: "Authoritative Suppression",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 1325) to the target Troop, and heals own Troop (Heal Factor 310).",
        skilltwoname: "Zeal",
        skilltwotype: "Counterattack",
        skilltwoprob: "20",
        skilltwodescr: "When deployed Troop receives healing, there is a 20 % chance to deal 1 instance of direct damage (Damage Factor 750) to the target Troop, and a 20 % chance to randomly Purify 1 debuffs from your own Troop. Triggers up to 1 time every 3s.",
        skillawakename: "Vanquishing Blade",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1700) to the target Troop, and heals own Troop (Heal Factor 400), and reduces damage taken by 10 % for 2s",
        talentonename: "Hold Fast",
        talentonetype: "Passive",
        talentonedescr: "When deployed Troop counterattacks, there is a ??? % chance to grant them a shield (Shield Factor ???) for 2s. Triggers up to 1 time every 4s.",
        talenttwoname: "Tit for Tat",
        talentwotype: "Counterattack",
        talenttwodescr: "When deployed Troop receives Active Skill Damage, deals 1 instance of direct damage (Damage Factor ???) to the target Troop. If your own Troop does not have a shield, they receive ?? % less damage for 1s. Triggers up to 1 time every 1s.",
        talentthreename: "Determined Defense",
        talentthreetype: "Counterattack",
        talentthreedescr: "When deployed Troop receives a basic attack, there is a ?? % chance to deal 1 instance of direct damage (Damage Factor ???) to the target Troop, and heal your own Troop (Heal Factor ???). If your own Troop has a shield, the target Troop receives Broken Blade for 1s. Triggers up to 1 time every 3 seconds.",
        id: 36
    },
    {
        name: "Charlton",
        skillonename: "Death Omen Crossbow",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 900) to the target and inflicts them with Poison. Poisoned enemies will take continuous damage every second (Damage Factor 220) for 3 seconds. Also increases own Troop's evasion by 15 % for 1 seconds.",
        skilltwoname: "Foresight",
        skilltwotype: "Command",
        skilltwoprob: "100",
        skilltwodescr: "Every 9 seconds, inflict a Burning effect on the target Troop, causing continuous damage per second (Damage Factor 350) for 3 seconds. If deployed Troop is flanked in Outer City Battles, it deals 1 additional instance of direct damage (Damage Factor 500) to the target Troop, and heals itself 1 time (Heal Factor 500).",
        skillawakename: "Face Perils Together",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,200) to the target and inflicts them with Poison. Poisoned enemies will take continuous damage every second (Damage Factor 300) for 3 seconds. Also increases own Troop's evasion by 20 % for 1 seconds, and increases the damage taken by the target by 25 % for 1 seconds.",
        talentonename: "Eagle Flame Pursuit",
        talentonetype: "Passive",
        talentonedescr: "The active skill damage of deployed Troop is increased by 20 %, and Burning damage dealt is increased by 20 %.",
        talenttwoname: "Shadowed Gaze Ambush",
        talentwotype: "Command",
        talenttwodescr: "Every 9 seconds, deals 1 instance of direct damage (Damage Factor 750) to the target, randomly dispels 1 buff from the target, and restores 200 Rage to your own Troop. If your Troop is under the evasion effect, additionally inflicts Poison on the target Troop. Poisoned enemies will take continuous damage every second (Damage Factor 600) for 2 seconds.",
        talentthreename: "Heralding Eagles Cry",
        talentthreetype: "Command",
        talentthreedescr: "Every 6 seconds, if the target is Poisoned, there is a 100 % chance to deal 1 instance of direct damage (Damage Factor 500) and increase the target's damage received by 20 % for 2 seconds. If the target is Burning, your Troop has a 100 % chance to receive healing (Heal Factor 500) 1 time, and increase evasion by 40 % for 1 seconds.",
        id: 37
    },
    {
        name: "Heidrun",
        skillonename: "Poison Blades Kiss",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 480) to the target and inflicts them with Poison. Poisoned enemies will take continuous damage every second (Damage Factor 360) for 3 seconds. If the target is inflicted with Poison, deals 1 instance of direct damage to the target (Damage Factor 320).",
        skilltwoname: "Burning Blade Scorching Heart",
        skilltwotype: "Command",
        skilltwoprob: "100",
        skilltwodescr: "Every 9 seconds, inflict a Burning effect on the target Troop, causing continuous damage per second (Damage Factor 325) for 3 seconds. If your Troop has fewer units than the target Troop, heal this Hero's Troop 1 time (Heal Factor 650). If your Troop has more units than the target Troop, deal 1 instance of direct damage to the target (Damage Factor 650).",
        skillawakename: "Dance of Death",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 600) to the target and inflicts them with Poison. Poisoned enemies will take continuous damage every second (Damage Factor 450) for 3 seconds. If the target is inflicted with Poison, deals 1 instance of direct damage to the target (Damage Factor 400). If the target is inflicted with Burning, deployed Troop's evasion increases by 40 % for 1 seconds.",
        talentonename: "Bloody Slash Venomous Bite",
        talentonetype: "Passive",
        talentonedescr: "The Active Skill damage of deployed Troop is increased by 20 %, and Poison damage is increased by 20 %.",
        talenttwoname: "Armor-corroding Blood",
        talentwotype: "Passive",
        talenttwodescr: "When deployed Troop receives healing, there is a 50 % chance to inflict Poison on the target, dealing continuous damage every second (Damage Factor 350) for 2 seconds, and reduce deployed Troop's damage received by 30 % for 1 seconds. If target is inflicted with Burning, dispels 1 random buff on the target.",
        talentthreename: "Returning Blood Flame Edge",
        talentthreetype: "Command",
        talentthreedescr: "Inflict target with Burning every 6s, dealing continuous damage (Damage Factor 400) every second for 2 seconds. There is a 50 % chance to increase deployed Troop's evasion by 40 % for 1 seconds, a 50 % chance to restore 300 Rage to this Hero's Troop, and a 50 % chance to Purify 1 random debuff on this Hero's Troop.",
        id: 38
    },
    {
        name: "Greta",
        skillonename: "Falling Impact",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage (Damage Factor 1,300) to up to 4 target Troops within a circular area. If deployed Troop has more units than the target, the target will be inflicted with Bleed. Bleeding enemies will take continuous damage every second (Damage Factor 320) for 2s. If deployed Troop has fewer units than the target, grants Retribution to the deployed Troop, increasing Retribution Rate by 40 % for 2s.",
        skilltwoname: "Broken Blade Charge",
        skilltwotype: "Cooperation",
        skilltwoprob: "100",
        skilltwodescr: "When deployed Troop performs a basic attack, if deployed Troop is inflicted with Retribution, there is a 25 % chance that they will get a shield (Shield Factor 400) for 2s, and a 25 % chance to inflict Slow on target Troops, reducing their March Speed by 30 % for 2s. If target Troops are inflicted with Silence, there is a 50 % chance to deal 1 instance of direct damage to the target (Damage Factor 500). If target Troops are inflicted with Bleed, there is a 20 % chance that deployed Troop will receive 1 instance of healing (Heal Factor 400).",
        skillawakename: "Time of Severance",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage (Damage Factor 1,600) to up to 4 target Troops within a circular area. If deployed Troop has more units than the target, the target will be inflicted with Bleed. Bleeding enemies will take continuous damage every second (Damage Factor 400) for 2s. If deployed Troop has fewer units than the target, grants Retribution to the deployed Troop, increasing Retribution Rate by 50 % for 2s. If target Troops are inflicted with Slow, deals 1 additional instance of direct damage (Damage Factor 600) to target Troops.",
        talentonename: "Shattered Edge",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troops Basic Attack Damage by 20 %, and Bleed Damage dealt by 20 %.",
        talenttwoname: "Oathbreakers Blade",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troop activates an Active Skill, target Troop is inflicted with Silence for 1s. If deployed Troop has more units than the target, deals 1 instance of direct damage to target (Damage Factor 800). If deployed Troop has fewer units than the target, reduces the damage taken by deployed Troop by 20 % for 1s, and deployed Troop receives 1 instance of healing (Heal Factor 600).",
        talentthreename: "Exiled Bloodblade",
        talentthreetype: "Cooperation",
        talentthreedescr: "When deployed Troop performs a basic attack, there is a 20 % chance to inflict the target Troop with Bleed (Damage Factor 400) for 1s, and deployed Troop gains Retribution, increasing Retribution Rate by 50 % for 1 s. When this effect is triggered, if target Troop is already inflicted with Bleed, they will be inflicted with Silence for 1s. If the deployed Troop already has Retribution, it will gain a shield (Shield Factor 400) for 1s.",
        id: 39
    },
    {
        name: "Sigrid",
        skillonename: "Blade of Conquest",
        skillonetype: "Active",
        skilloneprob: 100,
        skillonedescr: "Deals 1 instance of direct damage to the target Troop (Damage Factor 1,440), grants your Troop the Retribution effect, increasing Retribution Rate by 40 % for 2 seconds. If the target Troop is inflicted with Bleed, your Troop will be healed 1 time (Heal Factor 320).",
        skilltwoname: "Winters Coronation",
        skilltwotype: "Cooperation",
        skilltwoprob: "100",
        skilltwodescr: "When deployed Troop activates an Active Skill, it causes the target Troop to suffer from Bleed, taking continuous damage per second (Damage Factor ???) for 2 seconds. If the deployed Troop's units are higher than the target Troop's units, the target Troop is slowed, reducing March Speed by 30 % for 2 seconds. If the deployed Troop's units are lower than the target Troop's units, the deployed Troop gains a shield (Shield Factor ???) for 2 seconds and purifies 1 debuffs from itself.",
        skillawakename: "Triumphant Presence",
        skillawaketype: "Active",
        skillawakeprob: 100,
        skillawakedescr: "Deals 1 instance of direct damage to the target Troop (Damage Factor 1,800), grants your Troop the Retribution effect, increasing Retribution Rate by 50 % for 2 seconds. If the target Troop is inflicted with Bleed, your Troop will be healed 1 time (Heal Factor 400). If the target Troop is inflicted with Slow, deals 1 additional instance of direct damage to the target Troop (Damage Factor 400).",
        talentonename: "Northern Blood Feast",
        talentonetype: "Passive",
        talentonedescr: "Increases deployed Troop's Basic Attack Damage by 30 %. When performing a basic attack, if target is inflicted with Slow, there is a 50 % chance to inflict Bleed on the target Troops (Damage Factor 150) for 1s.",
        talenttwoname: "Cold Iron Oath",
        talentwotype: "Cooperation",
        talenttwodescr: "When deployed Troop performs a basic attack, there is a 20 % chance to deal 1 instance of direct damage (Damage Factor 400). When dealing damage, if the target Troop is inflicted with Slow, 1 additional distance of direct damage (Damage Factor 400) will be dealt to target Troops. If target Troop is inflicted with Bleed, there is a 50 % chance that your Troop will be healed 1 time (Heal Factor 400).",
        talentthreename: "Royal Authority",
        talentthreetype: "Cooperation",
        talentthreedescr: "When deployed Troop performs a basic attack, there is a 15 % chance to grant them Retribution, increasing Retribution Rate by 50 % for 2s. If deployed Troop is inflicted with Retribution, there is a 50 % chance to inflict Silence on target Troops for 1 s. If target Troops are inflicted with Bleed, there is a 50 % chance to increase the damage received by target Troop by 20 % for 1s.",
        id: 40
    }
];